# Generated by Django 4.1.2 on 2022-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myauto',
            options={'verbose_name': 'Автомобили в наличии', 'verbose_name_plural': 'Автомобили в наличии'},
        ),
        migrations.AddField(
            model_name='myauto',
            name='coast',
            field=models.CharField(default=0, max_length=20, verbose_name='Цена Авто'),
            preserve_default=False,
        ),
    ]
