# Generated by Django 4.1.2 on 2022-10-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myauto_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myauto',
            name='img',
        ),
    ]
