# Generated by Django 4.1.2 on 2022-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_myauto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauto',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', verbose_name='Изображение', width_field=100),
        ),
    ]
