# Generated by Django 4.1.2 on 2022-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_applications_alter_myauto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauto',
            name='type',
            field=models.CharField(default=1, max_length=250, verbose_name='Тип кузова'),
            preserve_default=False,
        ),
    ]
