# Generated by Django 4.1.2 on 2022-10-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myauto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauto',
            name='born_year',
            field=models.CharField(default=1, max_length=30, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myauto',
            name='engine',
            field=models.CharField(default=1, max_length=30, verbose_name='Двигатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myauto',
            name='engine_ob',
            field=models.CharField(default=1, max_length=30, verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myauto',
            name='privod',
            field=models.CharField(default=1, max_length=30, verbose_name='Привод'),
            preserve_default=False,
        ),
    ]
