# Generated by Django 4.1.2 on 2022-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_myauto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauto',
            name='engine',
            field=models.CharField(choices=[('Купе', 'Бензин'), ('Седан', 'Дизель'), ('Минивен', 'Гибрид'), ('Кабриолет', 'Электро')], max_length=30),
        ),
    ]
