# Generated by Django 4.1.2 on 2022-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_myauto_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauto',
            name='engine',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], max_length=30),
        ),
        migrations.AlterField(
            model_name='myauto',
            name='privod',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='myauto',
            name='type',
            field=models.CharField(choices=[('Купе', 'Купе'), ('Седан', 'Седан'), ('Минивен', 'Минивен'), ('Кабриолет', 'Кабриолет'), ('Кроссовер', 'Кроссовер'), ('Пикап', 'Пикап'), ('Хэтчбек', 'Хэтчбек'), ('Универсал', 'Универсал')], max_length=25),
        ),
    ]
