# Generated by Django 4.1.2 on 2022-11-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_myauto_engine_alter_myauto_privod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauto',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
