# Generated by Django 4.1.2 on 2022-11-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_myauto_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauto',
            name='kpp',
            field=models.CharField(choices=[('Ручная', 'Ручная'), ('Механика', 'Механика'), ('Типтроник', 'Типтроник'), ('Адаптивная', 'Адаптивная')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myauto',
            name='probeg',
            field=models.CharField(default=2, max_length=30, verbose_name='Пробег'),
            preserve_default=False,
        ),
    ]
