# Generated by Django 4.1.2 on 2022-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_myauto_kpp_myauto_probeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myauto',
            name='img1',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myauto',
            name='img2',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myauto',
            name='img3',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myauto',
            name='img4',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение 4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myauto',
            name='img5',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='Изображение 5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myauto',
            name='kpp',
            field=models.CharField(choices=[('Автоматическая', 'Автоматическая'), ('Механика', 'Механика'), ('Типтроник', 'Типтроник'), ('Адаптивная', 'Адаптивная')], max_length=30),
        ),
    ]
